bump, unfortunately need to disable ddcci-driver
Had a build problem:

error: builder for '/nix/store/qnm13yjikm9j21qfp64xydg94q124x2r-ddcci-driver-6.10-0.4.4.drv' failed with exit code 2;
       last 10 log lines:
       >  1827 |         .class          = I2C_CLASS_SPD,
       >       |                           ^~~~~~~~~~~~~
       >       |                           I2C_CLASS_HWMON
       > make[4]: *** [/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/source/scripts/Makefile.build:244: /build/source/ddcci/ddcci.o] Error 1
       > make[3]: *** [/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/source/Makefile:1934: /build/source/ddcci] Error 2
       > make[2]: *** [/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/source/Makefile:240: __sub-make] Error 2
       > make[2]: Leaving directory '/nix/store/ayycw4pj0k5hgyxajynihjnszzfrxq26-linux-6.10-dev/lib/modules/6.10.0/build'
       > make[1]: *** [Makefile:38: ddcci.ko] Error 2
       > make[1]: Leaving directory '/build/source/ddcci'
       > make: *** [Makefile:28: ddcci] Error 2
       For full logs, run 'nix log /nix/store/qnm13yjikm9j21qfp64xydg94q124x2r-ddcci-driver-6.10-0.4.4.drv'.